name = "RudinAnalysis"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RudinAnalysis"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `λ a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.lambdaSyntax = false
weak.linter.style.emptyLine = false
weak.linter.style.whitespace = false

[[require]]
name = "Paperproof"
git = "https://github.com/Paper-Proof/paperproof.git"
subDir = "lean"
rev = "main"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"
[[lean_lib]]
name = "RudinAnalysis"
